# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DLAutoSlidePageViewController Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DLAutoSlidePageViewController
  pod 'DLAutoSlidePageViewController', :path => '../'

  target 'DLAutoSlidePageViewControllerTests' do
          inherit! :search_paths
          pod 'DLAutoSlidePageViewController', :path => '../'
  end

end
