default_platform(:ios)

ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "4"

platform :ios do

  	lane :tests do
  	run_tests(
  	  workspace: "DLAutoSlidePageViewController.xcworkspace",
     	  devices: ["iPhone 14"],
      	  scheme: "DLAutoSlidePageViewController Tests",
	  code_coverage: true
    	)
	end

end
