name: Testing

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Install Bundle
      run: bundle install
    - name: Dependencies
      working-directory: ./Example
      run: pod install
    - name: Run unit tests
      working-directory: ./Example
      run: bundle exec fastlane tests
